apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekEwTVRVeQpNREE1TXpGYUZ3MDBNekEwTVRVeU1EQTVNekZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQnVhNy9MWGhTZzJQeThOQXJtS3c3dFIyUXpncGpNK3RCa2hnMm5RdWt3RWw1TG04YwpJbVJIV1dpVmtsYzVqNCtWcTc5Tjk0emlVVFAzcXVWQzhHdWl2V3JtaTVYdEEySHJjekphZGJYWFlIUmpQbUZpClJsMDNIOWlYSThwcXpzTWZiMER6OVl1cW43R2dtNktNeE9pZ1BlZkx4bXR0b1J2Q1FaZ1RZVEhYblVkTlFPYm8Kd2hJMUFkRUVqdng1UHFGQ0JMdU5OR1F6c1ExRS80Nk45YmIvS1NtLzNYM1NLOHpxaFo1MGZSSm4wcnBsMHJqYgpJbElZVnpnOWIyNGZ2dXZxMHdXSHF5RU80aUxQSDU2bVpxZFlsOGJWSUN4UW1KUWtzWlZhRkNzN0xTTEIvMWJ6CnZsRGluZUVrcUFoZEo3TnBqZ2FGQkU5b1pjcytoejdYdFk0QkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJwTU00cHVPYUtvVCtNUFNGbQpPbTU0WEhxYWlUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHV0NiajlzMGJTanp6YkpHMnpGdVM4R2tzTUJRClAxWjM2Y2JUZ2tlRzh3UXZTdm1Ta2xqTG5zK3RocHhLdkdZQms3emZZSnRVbnhsNW9JOTZLcGpNSm9wODNEOGMKTEU1TkRMZWdUd1c2UkxLYzJ4SkUxR3Rxa2ZxalhuV3F1c1BTMWNMdmF1N3Vna0pHaEErWS96amsyTHlvb0dwaApIOXZreDUrM0p0MmJaL3ZEbm9LRklSc2F3VTRaTHRFamxsaDJzZ0lqRjZESDc1bkhPeXFhUUxZbUNSOGxxRWdwCnVIYWFLanFvRStxbnBwZXdzNU8ybkxoZWtzK3lNOW5GYUtLUnFaUWN3UGVuK1JDMG9kZEdlc3gwazEycGowbGEKaytaajFrbHdHaktuSGFrcDlMRlZiOXE2WGxSTC9GQTNpS3V0c3hnVVRsak1sZE83NjJVWUZZZnF3UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://eb57bd87-602c-42d8-bdb7-f18fdb10dc15.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_e2e8be057c1ef06a2c5ae8fba8995dbcd765ebbe6eddaf3d911e90a1f72bd36c
